# Generated by Django 4.0.4 on 2022-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('zcode', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
    ]
