# Generated by Django 4.0.4 on 2022-06-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land_lot_number_address', models.CharField(max_length=100)),
                ('road_name_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.category')),
                ('zcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.region')),
            ],
            options={
                'db_table': 'cafes',
            },
        ),
    ]
