# Generated by Django 4.0.4 on 2022-06-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='zcode',
            new_name='region',
        ),
    ]
