# Generated by Django 4.0.4 on 2022-06-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_station', models.PositiveSmallIntegerField()),
                ('output', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'chargers',
            },
        ),
        migrations.CreateModel(
            name='ChargerType',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('explanation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'charger_types',
            },
        ),
        migrations.CreateModel(
            name='ChargingStatus',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('explanation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'charging_statuses',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('detail_location', models.CharField(max_length=100, null=True)),
                ('road_name_address', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('hours_of_operation', models.CharField(blank=True, max_length=100)),
                ('business_id', models.CharField(db_index=True, max_length=10)),
                ('business_name', models.CharField(max_length=30)),
                ('business_manamgement_name', models.CharField(max_length=30)),
                ('business_call', models.CharField(max_length=30, null=True)),
                ('parking_free_yes_or_no', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('parking_detail', models.CharField(blank=True, max_length=200)),
                ('limit_yes_or_no', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('limit_detail', models.CharField(blank=True, max_length=200)),
                ('delete_yes_or_no', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('delete_detail', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.category')),
                ('zcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.region')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='ChargerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charger_status_update_datetime', models.DateTimeField()),
                ('last_charging_start_datetime', models.DateTimeField()),
                ('last_charging_end_datetime', models.DateTimeField()),
                ('now_charging_start_datetime', models.DateTimeField()),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evs.charger')),
                ('charging_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evs.chargingstatus')),
            ],
            options={
                'db_table': 'charger_histories',
            },
        ),
        migrations.AddField(
            model_name='charger',
            name='charger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evs.chargertype'),
        ),
        migrations.AddField(
            model_name='charger',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evs.station'),
        ),
    ]
