# Generated by Django 4.0.4 on 2022-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='zcode',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='chargerhistory',
            name='charger_status_update_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargerhistory',
            name='last_charging_end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargerhistory',
            name='last_charging_start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargerhistory',
            name='now_charging_start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
