# Generated by Django 4.0.4 on 2022-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0002_rename_zcode_station_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerhistory',
            name='charger_status_update_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargerhistory',
            name='last_charging_end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargerhistory',
            name='last_charging_start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargerhistory',
            name='now_charging_start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
