# Generated by Django 4.0.4 on 2022-06-07 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0003_alter_chargerhistory_charger_status_update_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerhistory',
            name='charging_status',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='evs.chargingstatus'),
        ),
    ]
