# Generated by Django 4.0.4 on 2022-06-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0004_alter_chargerhistory_charging_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='charging_status',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='evs.chargingstatus'),
        ),
    ]
